config/routes.rb
Rails.application.routes.draw do

  root 'jobs#index'
  resources :users
  resources :jobs, :ratings
  resources :categories, :except => [:edit]
  resources :applicants

  get "/coordinates" => 'jobs#coordinates'

  put '/jobs/:id/status_in_progress' => 'jobs#status_in_progress'
  patch '/jobs/:id/status_in_progress' => 'jobs#status_in_progress'

  put '/jobs/:id/status_completed' => 'jobs#status_completed'
  patch '/jobs/:id/status_completed' => 'jobs#status_completed'

  resources :jobs do
    resources :applicants, :only => [:create]
    resources :comments
  end

  # Ratings need to be broken into rate_user and rate_job.

  post '/jobs/:id/rate' => 'jobs#rate', :as => "rate_job"
  post '/job/:job_id/rate' => 'users#rate', :as => "rate_user"


  # Session
  get '/login' => 'session#new', :as => "login"
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy', :as => "logout"

end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
  belongs_to :user
  belongs_to :job

  # Very cool stuff Jack showed us, please DO NOT delete! It allows you to call applicant.name(name is a key/attribute in user which is associated with applicant. )
  delegate :name, :to => :user

end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :fetch_user, :authorise, :only => [:index, :show, :create]
  def index
    @applicants = Applicant.all
  end

  def show
    @applicant = Applicant.find(params[:id])
  end

  def new
    @applicant = Applicant.new
  end

  def create

    @applicant = Applicant.new(applicant_params)
    @applicant.job_id = params[:job_id]
    @applicant.user_id = @current_user.id

    # Creating a JSON format for aJax to get and being manipulated in the DOM.
    job = Job.find(params[:job_id])

    if @applicant.save
      # @info = {
      #   :quote => @applicant.quote,
      #   :description => @applicant.description,
      #   :user_id => @current_user.id,
      #   :job_id => job.id
      # }
      render json: @applicant
    else
      render json: @applicant.errors, status: :unprocessable_entity
    end

  end

  def edit
  end

  private

  def applicant_params
    params.require(:applicant).permit(:description, :quote, :user_id, :job_id)
  end

end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/views/applicants/edit.html.erb
<%= form_for(@applicant, remote: true) do |f| %>
  <p>
    <%= f.label :quote %>
    <%= f.text_field :quote, :required => true %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>


<% end %>

app/views/applicants/index.html.erb
<ul>
  <% @applicants.each do |a| %>
    <li>
      User: <%= a.user.name %>
    </li>
    <li>
      <a class="button" <%= link_to(a.job.task_title, applicant_path( a )) %>
    </li>
    <li>
      Quote: <%= a.quote %>
    </li>
    <li>
      Description: <%= a.description %>
    </li>
    <br>
  <% end %>
</ul>

app/views/applicants/show.html.erb
<h1>Applicants#show</h1>
<p>Find me in app/views/applicants/show.html.erb</p>

<h1>A list of applicants for <%= @applicant.job.task_title %></h1>

<h4>Applicants under <%= @applicant.job.task_title %></h4>

<% @applicant.each do |b| %>
  Title: <%= link_to(b.task_title, job_path( b )) %>
    Posted by: <%= b.user.name %>
  <br>
<% end %>

<!-- .order("created_at ASC") -->