config/routes.rb
Rails.application.routes.draw do

  root 'jobs#index'
  resources :users
  resources :jobs, :ratings
  resources :categories, :except => [:edit]
  resources :applicants

  get "/coordinates" => 'jobs#coordinates'

  put '/jobs/:id/status_in_progress' => 'jobs#status_in_progress'
  patch '/jobs/:id/status_in_progress' => 'jobs#status_in_progress'

  put '/jobs/:id/status_completed' => 'jobs#status_completed'
  patch '/jobs/:id/status_completed' => 'jobs#status_completed'

  resources :jobs do
    resources :applicants, :only => [:create]
    resources :comments
  end

  # Ratings need to be broken into rate_user and rate_job.

  post '/jobs/:id/rate' => 'jobs#rate', :as => "rate_job"
  post '/job/:job_id/rate' => 'users#rate', :as => "rate_user"


  # Session
  get '/login' => 'session#new', :as => "login"
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy', :as => "logout"

end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id               :integer          not null, primary key
#  task_title       :string
#  task_description :text
#  task_location    :string
#  due_date         :date
#  start_time       :time
#  workers_required :integer
#  budget           :float
#  images           :text
#  user_id          :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Job < ActiveRecord::Base
  belongs_to :user
  has_many :applicants
  has_many :comments
  has_and_belongs_to_many :categories
  has_many :ratings, as: :rateable

  enum status: [:proposal, :in_progress, :completed]

  # geocoder
  geocoded_by :task_location
  after_validation :geocode, :if => :task_location_changed?

  def slugs
    slugs_arr = self.categories.map do |c|
      c.slug
    end
    slugs_arr.join(" ")
  end

  def proposal?
    self.status == "proposal"
  end

  def in_progress?
    self.status == "in_progress"
  end

  def completed?
    self.status == "completed"
  end

  def status_c
    self.status.capitalize
  end

  # Awesome contribution by Badger the Legend! Creating an applicant method which finds the employee(returns an object) who was chosen by the employer to do the job!
  def applicant
    User.find(Applicant.find(self.applicant_id).user_id) if self.applicant_id
  end

end
 

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

    def index
      @jobs = Job.all.order("created_at DESC")
    #   geocoder
      if params[:search].present?
        distance = params[:distance] || 10
        @jobs = Job.near(params[:search], distance.to_i, :order => :task_location)
      else
        @jobs = Job.all.order("created_at DESC")
      end
    #   ///////
    end

    def new
      @job = Job.new
    end

    def coordinates
        @jobs = Job.all
        @coordinates = []
        @jobs.each do |j|
            @coordinates << [j.task_title, j.latitude, j.longitude]
        end
    render :json => @coordinates
    end

    def create

      job = Job.new(job_params)
      job.user_id = @current_user.id
      job.category_ids = params[:job][:category_ids]

      if params[:job][:images].present?
          params[:job][:images].each do |photo|
            req = Cloudinary::Uploader.upload(photo)
            job.images << req['public_id']
            job.save
          end
      end
      job.save
      redirect_to job_path(job)
    end

    def edit
      @job = Job.find params[:id]
    end

    def update

      @job = Job.find params[:id]
      @job.category_ids = params[:job][:category_ids]

      # respond to different formats here.
      # get it to return a json object that we can manipulate in our JS and render on the page
      respond_to do |format|
        if @job.update(job_params)
          format.html { redirect_to @job, notice: 'Job was successfully updated.' }
          # passing the applicant Method created in Job Model into the JSON file, which would nest the selected employee object in job JSON. Go Badger!!!!!!!!!!!!!
          format.json { render json: @job, methods: :applicant, status: :ok, location: @job }
        else
          format.html { render :edit }
          format.json { render json: @job.errors, status: :unprocessable_entity }
        end
      end

    end

    def show
      if !@current_user
        redirect_to login_path
      end
      @job = Job.find params[:id]
      @applicant = Applicant.new
      @applicants = Applicant.all
      @rating = Rating.new
      @ratings = Rating.all
      @comment = @job.comments.build(:job => @job)
    end

    def destroy
      job = Job.find params[:id]
      job.destroy
      redirect_to jobs_path
    end

    # Created to allow ratings under rating model for a job
    def rate

      @rating = Rating.new(rating_params)
      @rating.user_id = @current_user.id
    # Check to make sure user is not the employee
      if params[:user_id].to_i == @current_user.id
        render :json => { :moron => "You" }
        return
      end
      job = Job.find_by(:id => params[:id])
      job.ratings << @rating

        if @rating.save
          render json: @rating
        else
          render json: @rating.errors, status: :unprocessable_entity
        end
        # redirect_to job
    end

    def status_in_progress
        @job = Job.find params[:id]
        @job.status = 1
        @job.save

        render :json => @job
    end

    def status_completed
        @job = Job.find params[:id]
        @job.status = 2
        @job.save

        render :json => @job
    end

    private
    # References for the rating
    def rating_params
      params.require(:rating).permit(:body, :score, :job_id, :user_id)
    end


    def job_params
      params.require(:job).permit(:task_title, :task_description, :task_location, :due_date, :start_time, :workers_required, :budget, :user_id, :applicant_id, :category_id, :rating_id, :category_ids => [])
    end



end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<h3>Post new Job</h3>

<%= form_for(@job, multipart: true) do |f| %>
      <p>
        <%= f.label :task_title,"Task Title" %>
        <%= f.text_field :task_title, :required => true %>
      </p>
      <p>Please add the categories related to your job.
            <%= hidden_field_tag "job[category_ids][]", nil %>
                <% Category.all.each do |category| %>
                  <div class="button"><%= check_box_tag "job[category_ids][]", category.id, @job.category_ids.include?(category.id), id: dom_id(category) %><%= label_tag dom_id(category), category.name %></div>
            <% end %>
      </p>
      <p>
        <%= f.label :task_description,"Task Description" %>
        <%= f.text_field :task_description, :required => true %>
      </p>
      <p>

        <%= f.label :task_location, "Location of job" %>
        <%= f.text_field :task_location, :required => true %>
      </p>

      <p>
        <%= f.label :due_date, "Date of job" %>
        <%= f.date_field :due_date, :required => true %>
      </p>

      <p>
        <%= f.label :start_time, "Time of job" %>
        <%= f.time_field :start_time %>
      </p>

      <p>
        <%= f.label :budget, "Budget" %>
        <%= f.text_field :budget, :required => true %>
      </p>
      <p>
        <%= f.label :images %>
        <%= f.file_field :images, :multiple =>true %>
      </p>

      <br>

      <button class="btn waves-effect waves-light" id="postJob" type="submit" name="action">
        <i class="material-icons right">Post Job</i>
      </button>

<% end %>

app/views/jobs/_job_rating.html.erb
<div class="button" id="submitARating">
  Submit a rating
</div>
<!-- This is to rate the employer - job owner!!! -->
<!-- Including Template to show job_Ratings/review -->

  <div class="rating">
    <p>This job is complete - Please rate <%= link_to(@job.user.name, user_path(@job.user)) %></p>

    <%= form_for(@rating, :url => rate_job_path(@job.id), remote: true, format: :json) do |f| %>

      <p>
        <%= f.label :score %>
        <%= f.number_field :score, :min => 1, :max => 5, :required => true %>
      </p>
      <p>
        <%= f.label :body %>
        <%= f.text_field :body %>
        <% f.hidden_field :job_id %>
      </p>
      <p id="submit_job_rating">
        <%= f.submit "Submit" %>
      </p>
    <% end %>
  </div>

app/views/jobs/_user_rating.html.erb
<!-- This is to rate the employee!!!! -->


<!-- Including Template to show user_Ratings/review -->

  <div class="rating">
    <h6>Did this user <%= link_to(@job.applicant.name, user_path(@job.applicant.id)) if @job.applicant %> do a good job?</h6>
    <%= form_for(@rating, :url => rate_user_path(@job.id), remote: true, format: :json) do |f| %>
      <p>
        <%= f.label :score %>
        <%= f.number_field :score, :min => 1, :max => 5, :required => true %>
      </p>
      <p>
        <%= f.label :description %>
        <%= f.text_field :body %>
        <% f.hidden_field :user_id %>
      </p>
      <p id="submit_user_rating">
        <%= f.submit "Submit" %>
      </p>
    <% end %>
  </div>

app/views/jobs/edit.html.erb
<h2>Edit <%= @job.task_title %></h2>

<%= render :partial => 'form' %>

app/views/jobs/index.html.erb
<div id="buttons">
  <button class="all">Show All</button>
  <% Category.all.each do |category| %>
    <button class="<%= category.slug %>"><%= category.name %></button>
  <% end %>

</div>

<body>


<!-- geocoder -->
  <%= form_tag jobs_path, :method => :get do %>
    <p class ="text_field_tag">
      <%= text_field_tag :search, params[:search], :placeholder => "Enter Address"  %>
      </p>
      <p class ="number_field_tag">
      <%= number_field_tag :distance, params[:distance], :placeholder => "Distance"  %>
      </p>
      <p class ="search_by_location">
      <%= submit_tag "Search Near", :name => nil %>
      </p>
  <% end %>
  <!-- geocoder -->


<div class="cards">
  <% @jobs.each do |a| %>
    <div class="card small <%= a.slugs %>" id= "cardsmall">

      <div class="user">
        <%= cl_image_tag(a.user.image) %>
        <p>Posted by: <%= link_to(a.user.name, user_path(a.user)) %></p>

      </div>

      <p><%= link_to( a.task_title, "/jobs/#{a.id}" ) %> | Status: <span><%= a.status_c %></span></p>
      <p>Applied by <%= pluralize(a.applicants.length, "person") %></p>
      <p>Location: <%= a.task_location %></p>
      <p>Budget: <%= "$#{a.budget}" %></p>


    <% if a.categories.count == 0 %>
      No categories
    <% else %>
      Categories: <% a.categories.each do |b| %>
      <a class="button" <%= link_to(b.name, category_path(b)) %></a>
      <% end %>
      <br>
    <% end %>

    </div>
  <% end %>
</div>

app/views/jobs/new.html.erb
<%= render( :partial => "form" ) %>

app/views/jobs/show.html.erb
<script async defer src='https://maps.googleapis.com/maps/api/js?key=AIzaSyArkeFE3vFJz6vtxcv22Ev_fvs0X8-HGDo'></script>
<p id="job_id"><%= @job.id %></p>

<div class="control">
  <!-- Check for current user -->
  <% if @current_user.present? == false %>

  <% elsif @current_user.id == @job.user_id %>
    <span class="waves-effect waves-light btn" id="editWork">
      <%= link_to "Edit work", edit_job_path( @job.id ) %>
    </span>

    <span class="waves-effect waves-light btn" id="deleteWork">
      <%= link_to "Delete work", @job, :method => :delete, :data => { :confirm => "Are you sure?" } %>
    </span>
  <% end %>
</div>

<h5>Job Title: <%= @job.task_title %></h5>

<div class="scroller">
  <% @job.images.each do |image| %>
    <%= cl_image_tag(image, :crop => "fill", :width => 400, :height => 300) %>
  <% end %>
</div>

<!-- Main Info -->
<main class="row">
  <div class="col s6">
    <p>Description: <%= @job.task_description %></p>
    <p>Task Location: <%= @job.task_location %></p>
    <p>Date of Job: <%= @job.due_date %></p>
    <p>Time of Job: <%= @job.start_time %></p>
    <p>Budget: <%= "$#{@job.budget}" %></p>

    <% if @job.categories.count == 0 %>
      No Categories

    <% else %>
      Categories:
      <% @job.categories.each do |b| %>
        <a class="button" <%= link_to(b.name, category_path(b)) %></a>
      <% end %><br>
    <% end %>

    <% if @job.user %>
      <p>Job Posted By: <%= link_to(@job.user.name, @job.user) %></p>
    <% end %>

    <% if @job.categories.count == 0 %>
      No Categories
    <% else %>
      Categories:
      <% @job.categories.each do |b| %>
        <a class="button" <%= link_to(b.name, category_path(b)) %></a>
      <% end %><br>
    <% end %>

    <br>

    <!-- Tweet link -->
    <a href="https://twitter.com/share" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
  </div>

  <div class="col s6">
    <!-- Display Job Status -->
    <div class="status">
      <p>
        Status: <span><%= @job.status_c %></span>
      </p>
    </div>

    <!-- Job Completed Button -->
    <% if @current_user.id == @job.user.id %>
      <div class="waves-effect waves-light btn" id="completed">
        Job Completed
      </div>
    <% end %>

    <!-- If the user is looking for a job(employee), show the make an offer button and form -->
    <% if !@current_user %>
    <% elsif @current_user.employee? %>
      <div class="waves-effect waves-light btn" id="makeAnOffer">
        Make an Offer
      </div>
    <% end %>

    <!-- Form is creating an application for the current job -->
    <div id="offer">
      <%= form_for([@job, @applicant], remote: true) do |f| %>
        <p>
          <%= f.label :quote %>
          <%= f.number_field :quote, :required => true %>
        </p>
        <p>
          <%= f.label :description %>
          <%= f.text_field :description %>
        </p>
        <p id="submit_offer">
          <%= f.submit "Submit" %>
        </p>
      <% end %>
    </div>

    <!-- underscore Template to display offer data -->
      <script type="underscore/template" id="offerDisplayTemplate">
        <p>Your Quote: <%%= quote %></p>
        <p>Your Description: <%%= description %></p>
      </script>

    <!-- If the user is an employer, show people who have applied for the job, and choose an applicant. -->
    <% if @current_user.employer? %>
      <div id="applicants">

        <div class="show_applicants">
          <p>
            This job has been applied by <%= pluralize(@job.applicants.length, "user") %>
          </p>
          <% if @job.applicants.length > 0 %>
            <% @job.applicants.each do |a| %>
              <ul>
                <li>Applicant: <%= link_to(a.user.name, a.user) %></li>
                <li>Description: <%= a.description %></li>
              </ul>
            <% end %>
          <% end %>
        </div>

        <!-- Select an applicant only if there're more than 0 applicant-->
        <% if @job.applicants.length > 0 && @current_user.id == @job.user.id %>
          <% if !@job.completed? %>
            <div id="select_applicant">
              <!-- Sending an update request to job_controller. Using remote:true to include aJax request within this form -->
              <%= form_for(@job, remote: true, format: :json) do |f| %>
              <p>
                <%= f.label :select_an_applicant %>
                <%= f.collection_select(:applicant_id, @job.applicants, :id, :name) %>
                <%= f.submit "Submit" %>
              </p>
              <% end %>

              <!-- Underscore Template to display data -->
                <script type="underscore/template" id="applicantDisplayTemplate">
                  <h5>This job is taken by <%%= applicant.name %></h5>
                </script>
            </div>

          <% else %>
            <p>This job is taken by <%= @job.applicant.name %></p>
          <% end %>

        <% end %>

      </div>
    <% end %>
  </div>
</main>

<!-- rating -->
<div id = "rating_show" style="<%= 'display: none;' unless @job.completed? && @current_user.id == @job.user.id %>">
  <%# if @job.completed? && @current_user.id === @job.user.id %>
    <p>
      <%= render( :partial => "user_rating" ) %>
    </p>
  <%# end %>
</div>

<div id = "rating_job_show" style="<%= 'display: none;' unless @job.completed? && @current_user.id == @job.applicant.id %>">
  <%# if @job.completed? && @current_user.id == @job.applicant.id %>
    <p>
      <%= render( :partial => "job_rating" ) %>
    </p>
  <%# end %>
</div>

<hr>

<!-- Comments -->
<div class="comments">
  <table>
  <h5>Comments</h5>
    <tr>
      <td>
        <%= render @job.comments.order("created_at ASC") %>
          <h5>Add a comment below:</h5>
        <%= render 'comments/form' %>
    </td>
  </tr>
  </table>
</div>

  <%= content_tag :div, class: "lat", data: {lat: @job.latitude} do %>
  <%end%>
  <%= content_tag :div, class: "lng", data: {lng: @job.longitude} do %>
  <%end%>

<p id="lat_id"><%= @job.latitude %></p>

<p id="lng_id"><%= @job.longitude %></p>

<div id="map"></div>

<!-- geocoder  -->
<div class="row">

  <div class="col s6">
    <h3>Nearby Jobs</h3>
    <ul>
      <% for job in @job.nearbys(10) %>
        <li><%= link_to job.task_title, job %>
          <%= job.task_location%> (<%= job.distance.round(2) %> miles)</li>
      <% end %>
    </ul>
  </div>
</div>
<!-- geocoder -->