config/routes.rb
Rails.application.routes.draw do

  root 'jobs#index'
  resources :users
  resources :jobs, :ratings
  resources :categories, :except => [:edit]
  resources :applicants

  get "/coordinates" => 'jobs#coordinates'

  put '/jobs/:id/status_in_progress' => 'jobs#status_in_progress'
  patch '/jobs/:id/status_in_progress' => 'jobs#status_in_progress'

  put '/jobs/:id/status_completed' => 'jobs#status_completed'
  patch '/jobs/:id/status_completed' => 'jobs#status_completed'

  resources :jobs do
    resources :applicants, :only => [:create]
    resources :comments
  end

  # Ratings need to be broken into rate_user and rate_job.

  post '/jobs/:id/rate' => 'jobs#rate', :as => "rate_job"
  post '/job/:job_id/rate' => 'users#rate', :as => "rate_user"


  # Session
  get '/login' => 'session#new', :as => "login"
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy', :as => "logout"

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  job_id     :integer
#

class Category < ActiveRecord::Base
  has_and_belongs_to_many :jobs

  def slug
    self.name.downcase.gsub( /\W/, "" )
  end

  def get_sorted_jobs
      self.jobs.sort_by do |j|
          j.created_at
      end
  end
#
#   def get_sorted_comments
#       self.comments.sort_by do |c|
#           c.created_at
#       end
#   end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :authorise, :only => [:index, :show]

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find( params[:id] )
  end

  private
    def category_params
      params.require(:category).permit(:name, :category_id, :job_id)
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<h5>Here's a list of our categories</h5>

<% @categories.each do |a| %>
<a class="button" <%= link_to(a.name, category_path( a )) %></a><br>
<% end %>

app/views/categories/show.html.erb
<h1>A list of jobs for <%= @category.name %></h1>

<%= link_to( "Back to Categories", categories_path() )%>
<h4>Jobs under <%= @category.name %></h4>
<div>Sorted by most recent</div>
<% @category.get_sorted_jobs.each do |b| %>
  Title: <%= link_to(b.task_title, job_path( b )) %>
    Posted by: <%= b.user.name %>
  <br>
<% end %>