config/routes.rb
Rails.application.routes.draw do

  root 'jobs#index'
  resources :users
  resources :jobs, :ratings
  resources :categories, :except => [:edit]
  resources :applicants

  get "/coordinates" => 'jobs#coordinates'

  put '/jobs/:id/status_in_progress' => 'jobs#status_in_progress'
  patch '/jobs/:id/status_in_progress' => 'jobs#status_in_progress'

  put '/jobs/:id/status_completed' => 'jobs#status_completed'
  patch '/jobs/:id/status_completed' => 'jobs#status_completed'

  resources :jobs do
    resources :applicants, :only => [:create]
    resources :comments
  end

  # Ratings need to be broken into rate_user and rate_job.

  post '/jobs/:id/rate' => 'jobs#rate', :as => "rate_job"
  post '/job/:job_id/rate' => 'users#rate', :as => "rate_user"


  # Session
  get '/login' => 'session#new', :as => "login"
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy', :as => "logout"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CasualHire</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <!-- <%#= cloudinary_js_config %> only for uploading images with ajax -->
</head>
<body>
  <div class="wrapper">

    <nav>
      <div class="nav-wrapper #3f51b5 indigo">
        <a href="/jobs" class="brand-logo" id="logo">Casual Hire</a>
        <ul class="right hide-on-med-and-down">
          <li><%= link_to("All Jobs", jobs_path) %></li>
          <li><%= link_to("Categories", categories_path) %></li>

          <% unless @current_user.present? %>
            <li><%= link_to("Sign Up", new_user_path) %></li>
            <li><%= link_to("Log In", login_path()) %></li>
          <% else %>
            <% if @current_user.admin? %>
              <li><%= link_to("All Users", users_path) %></li>
            <% end %>

            <% if @current_user.employer? %>
              <li><%= link_to("Create a Job", new_job_path) %></li>
            <% end %>


            <li>You're logged in as <%= @current_user.role_c %></li>
            <li><%= link_to(@current_user.name, @current_user) %></li>
            <li id="navInfo"><%= link_to("Log Out", logout_path(), :method => :delete )  %></li>
          <% end %>
        </ul>
      </div>

    </nav>

    <% if flash[:success] %>
      <p class="flash">
        <%= flash[:success] %>
      </p>
    <% end %>

    <% if flash[:error] %>
      <p class="flash">
        <%= flash[:error] %>
      </p>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>

    <footer class="footer-copyright grey-text text-lighten-4 #3f51b5 indigo center">
      <p>
        Group project by Andrew, Arpan and Yangmei   © 2016 Copyright
      </p>
    </footer>
  </div>

</body>

</html>